import Head from 'next/head'
import Cover from '../shared/components/Cover'
import CountDown from '../shared/components/CountDown'
import OurStory from '../shared/components/OurStory'
import WeddingDetails from '../shared/components/WeddingDetails'
import RSVP from '../shared/components/RSVP'
import Registry from '../shared/components/Registry'
import Missing from '../shared/components/Missing'
import Adventures from '../shared/components/Adventures'

export default function Home() {
  return (
    <>
      <Head>
        <title>Chris and Morkie Adventure</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Cover />
        <CountDown />
        <OurStory />
        <WeddingDetails />
        <RSVP />
        <Registry />
        <Missing />
        <Adventures />
      </main>
    </>
  )
}
